### ISSUE TITLE
RTL8188 build error

### ISSUE THREAD

**Issue by mcsoft** [OpenNuvoton/NUC970_Buildroot#1]
I try to build a new image with realtek 8188 wifi support, but i get some errors.
Then try to build a more complex realtek chipset RTL8821, and this is builded without errors. I like to use 8188. Any suggestion to build?

**Comment by yachen** [comment]
Hi,

Please enable following kernel option and build again.

```
[*] Networking support ---> 
    -*- Wireless ---> 
        <*> Nuvoton external WiFi driver support
```
Sincerely,

Yi-An Chen

**Comment by mcsoft** [comment]
Dear Yi-An,

Thank you for quick answer. I cant find this option. Where is it?
I ran
make nuvoton_nuc972_defconfig for basic config, then make menuconfig
Only found drivers in Target packages ---> Hardware handling ---> rtl8188eu
Not found kernel options. What i do wrong?

Best Regards
Norb

**Comment by yachen** [comment]
Hi,

It's a Linux kernel option instead of buildroot option.


Sincerely,

Yi-An Chen

**Comment by mcsoft** [comment]
Hi,

Thank you, i found it.

Best Regards
Norb
