### ISSUE TITLE
uboot (2016.11-g5deddd) could not 

### ISSUE THREAD

**Issue by shkim3000** [OpenNuvoton/NUC970_Buildroot#10]
Hi,
I wana upgrade my nuc972 project so I cloned uboot and kernel from this.
I used default configuration on uboot and kernel.
I made uImage by below script
----------------
#!/bin/bash
MKIMAGE_TOOL=$UBOOT_DIR/tools/mkimage
$MKIMAGE_TOOL -A arm -O linux -T kernel -a 0x7FC0 -e 0x8000 -d 970image 970image.ub
------------------

I tried to run it on nuc970-evb.
It hang when starting kernel.

![캡처](https://user-images.githubusercontent.com/5379218/83333777-4954fc80-a2dd-11ea-80b4-5730bbf9ee5c.PNG)

what's wrong?

**Comment by yachen** [comment]
Hi,

Please try -a 0x8000 in your mkimage command.

**Comment by shkim3000** [comment]
thank you.
It works.

best regards,
David Kim


2020년 6월 1일 (월) 오후 12:40, Yi-An Chen <notifications@github.com>님이 작성:
