### ISSUE TITLE
Could you add NUC97x flash image generator

### ISSUE THREAD

**Issue by chenxy1988** [OpenNuvoton/NUC970_Buildroot#13]
Dear team,

I am using buildroot for new product in our company, all things solved successfully with a "make" command, but currently, we want to the buildroot generate a MP flash image directly without using WINDOWS MP application. Could you add this feature to buildroot or leave a NUC97x Flash image format with us?

Thanks!

Br,
Xiangyu

**Comment by yachen** [comment]
Hi,

Do you have NuWriter user manual? Section 4.5 describes the packet image format.

Sincerely,

Yi-An Chen

**Comment by chenxy1988** [comment]
Hi @yachen ,

Sorry, I don't have this documents, in fact, our FAE has less support, could you leave a link so that I would download it myself ?
Thank you.


Best regards,
Xiangyu

**Comment by yachen** [comment]
Hi, please check attached file. Thanks.

[NUC970 N9H30 NuWriter User Manual EN.pdf](https://github.com/OpenNuvoton/NUC970_Buildroot/files/4993498/NUC970.N9H30.NuWriter.User.Manual.EN.pdf)

**Comment by chenxy1988** [comment]
Hi @yachen ,
Thanks for your great help!
