### ISSUE TITLE
Need to backport e2fsprogs package from buildroot master

### ISSUE THREAD

**Issue by chenxy1988** [OpenNuvoton/NUC970_Buildroot#14]
Hi,

Package e2fsprogs need to backport from buildroot upstream, glibc 2.27 will have a copy_file_range library call to wrap the new copy_file_range system call,  this conflicts with the function in misc/create_inode.c; that would cause compile error when enable this package on target board.

Thanks.
[https://github.com/buildroot/buildroot/commits/master/package/e2fsprogs
](url)

Br,
Xiangyu

**Comment by yachen** [comment]
Done, thanks.

**Comment by chenxy1988** [comment]
thanks and close this issue.
