### ISSUE TITLE
Not able to write image files may be due to over programming.

### ISSUE THREAD

**Issue by tkrelcon** [OpenNuvoton/NUC970_Buildroot#16]
In NUC972 neither i am able to burn files in any of flash mode nor eras previously burned files in nuc972. Please guide for same. Thank you.

**Comment by tkrelcon** [comment]
> In NUC972 neither i am able to burn files in any of flash mode nor eras previously burned files in nuc972. Please guide for same. Thank you.

May be due to over programming

**Comment by tkrelcon** [comment]
Yes. NuWriter.

**Comment by tkrelcon** [comment]
Can you send me updated (latest) image files for kernel and boot. Because i think what i have too old..

**Comment by yachen** [comment]
Please provide UART0 log message for NuWriter connection and program failure.

**Comment by tkrelcon** [comment]
![Untitled](https://user-images.githubusercontent.com/79750687/109601321-a4ee3800-7b44-11eb-8437-c39e1ae4f4ba.png)
![image](https://user-images.githubusercontent.com/79750687/109601361-b6374480-7b44-11eb-9771-e60ba79f7d12.png)

**Comment by yachen** [comment]
Are you using latest NuWriter? https://github.com/OpenNuvoton/NUC970_NuWriter
You should get log file like below:

```
NUC970 IBR 20151008.1735
No Key
Boot from USB
=======================================
Run firmware code
CPU: 300MHz, DDR: 150MHz, SYS: 300MHz, PCLK: 75MHz
Parse NuWriter command line
=======================================
ID=0x0000EF15  _spi_type =0
SM ID [C2][DA][90][95]
Auto Detect:
BlockPerFlash= 2,047, PagePerBlock= 64
PageSize= 2,048, ECC= T4, ExtraDataSize= 64, SectorPerBlock= 256

SM ID [C2][DA][90][95]
Auto Detect:
BlockPerFlash= 2,047, PagePerBlock= 64
PageSize= 2,048, ECC= T4, ExtraDataSize= 64, SectorPerBlock= 256

g_uIsUserConfig=0
UXmodem_NAND BlockPerFlash=2,047
UXmodem_NAND PagePerBlock=64
UXmodem_NAND PageSize=2,048
```

**Comment by tkrelcon** [comment]
Thank You So Much Sir. Can you send any guide or video for first time user to test board. Or pre compiled image files to upload.. If you can it will be great help.

**Comment by yachen** [comment]
So you don't have NuWriter user manual in hand? Please check attached file.
[NUC970 N9H30 NuWriter User Manual EN.pdf](https://github.com/OpenNuvoton/NUC970_Buildroot/files/6066389/NUC970.N9H30.NuWriter.User.Manual.EN.pdf)

**Comment by tkrelcon** [comment]
Thank you sir. I have have new writer manual but i was asking about how to check board's working for demo files and how to develop custom application for perticular project.

**Comment by yachen** [comment]
It's straightforward to test storage or network with busybox build in commands. What component do you want to test?
We don't have user manual for develop custom application.  Can you be more specific about the question? Thanks.
