### ISSUE TITLE
Bad data crc when booting kernel Nuvoton tomato

### ISSUE THREAD

**Issue by Pfhilip** [OpenNuvoton/NUC970_Buildroot#20]
Hi, 

I have built a kernel using the defconfig at configs/nuvoton_nuc976_tomato_defconfig for the nuvoton tomato, I am trying to load it from an sd card but get an error verifying the checksum

![image](https://user-images.githubusercontent.com/90525039/135694023-09e87c36-75eb-4887-a2a0-71965582b460.png)

**Comment by warlock31415** [comment]
I had the same issue 2 days ago as well. Assuming you have a good kernel image try the following
```
set verify no
saveenv
fatload mmc 0:0 0x8000 uImage
bootm 0x8000
```

**Comment by Pfhilip** [comment]
> I had the same issue 2 days ago as well. Assuming you have a good kernel image try the following
> 
> ```
> set verify no
> saveenv
> fatload mmc 0:0 0x8000 uImage
> bootm 0x8000
> ```

This works but the error suggest there IS something wrong with the kernel image... so not optimal...

**Comment by yachen** [comment]
Shouldn't the address be 7fc0 instead of 8000?

**Comment by yachen** [comment]
Yes, the command copied image to volatile storage.  Data may retain if the period DDR doesn't refresh is very short.

**Comment by yachen** [comment]
Ah, yes. To speed up the Tomato board boot time, we use H/W SHA engine to calculate the uimage checksum. The mkimage tool in [970 uboot](https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11) supports ```-S sha1``` option that generate a SHA1 checksum instead of CRC32.
