### ISSUE TITLE
Linux kernel does not detect SD card

### ISSUE THREAD

**Issue by warlock31415** [OpenNuvoton/NUC970_Buildroot#24]
I have 2 partitions on the sd card, 1 with the uImage (formatted fat32) and one with the rootfs (ext4). But when i do
```
fatload mmc 0:1 0x7fc0 uImage 
bootm 0x7fc0
```

The kernel panics because it can't load the rootfs. When i supply bootargs set bootargs `root=/dev/mmcplk0p2 console=ttyS0,115200n8 rootfs=ext4` the boot process hangs and I don't see any output on the console. The mmc drivers are enabled in `linux-menuconfig` 
![image](https://user-images.githubusercontent.com/26103385/136223323-ca14bc62-5cfc-4f0d-a0d3-d06590469401.png)

If I boot from a kernel with initramfs I don't see any `mmcblk` device under `/dev/`

**Comment by yachen** [comment]
> If I boot from a kernel with initramfs I don't see any mmcblk device under /dev/

Which board are you using? Could be wrong switch setting on the board, wrong multi-function pin setting, or simply driver not enabled.

**Comment by warlock31415** [comment]
I have a `/sys/clas/mmc_host` but nothing in it nor does it show up under `/dev`

**Comment by yachen** [comment]
I can see the SD partitions without problem. There's no need to enable USHC, PXAV3, SDHCI, and MMC/SD/SDIO over SPI.
Attached is the kernel image I used, can you give it a try? Load to 0x8000 and execute.

```
~ # cat /proc/partitions
major minor  #blocks  name

 179        0   15187968 mmcblk0
 179        1     182118 mmcblk0p1
 179        2      32922 mmcblk0p2
```
[970image.zip](https://github.com/OpenNuvoton/NUC970_Buildroot/files/7327259/970image.zip)

**Comment by warlock31415** [comment]
is it a uImage? 
```
U-Boot> fatload mmc 0:1 0x8000 970image
reading 970image
9589376 bytes read in 1537 ms (5.9 MiB/s)
U-Boot> bootm 0x8000
Wrong Image Format for bootm command
ERROR: can't get kernel image!
```

**Comment by yachen** [comment]
It's not an uImage, you can use ```go 8000``` to execute it.

**Comment by yachen** [comment]
Can you attach your kernel config here?

**Comment by warlock31415** [comment]
[config.zip](https://github.com/OpenNuvoton/NUC970_Buildroot/files/7334496/config.zip)
Here's the attached .config and the linux config (from output/build/linux-master/.config)

**Comment by yachen** [comment]
```devtmpfs: error mounting -2```
The mount point of devtmpfs is /dev, can you check if the /dev directory exist on your SD card or not?
