### ISSUE TITLE
U-Boot Device Tree Blob Error

### ISSUE THREAD

**Issue by RSTurgay** [OpenNuvoton/NUC970_Buildroot#30]
Hi,

~/build/uboot-master/arch/arm/dts

![Screenshot 2022-04-04 222117](https://user-images.githubusercontent.com/80816677/161616718-7cae692d-51f3-49d3-8b9a-279d4240167b.png)

U-Boot Configuration

![Screenshot 2022-04-04 221929](https://user-images.githubusercontent.com/80816677/161616860-71fb5732-f2a7-4b02-b279-2b34b44edb6a.png)

Error ;

`  LD      u-boot
common/built-in.o: In function `show_board_info':
/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/common/board_info.c:24: undefined reference to `fdt_getprop'
lib/built-in.o: In function `fdtdec_get_int':
/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/lib/fdtdec_common.c:29: undefined reference to `fdt_getprop'
lib/built-in.o: In function `fdtdec_prepare_fdt':
/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/lib/fdtdec.c:593: undefined reference to `fdt_check_header'
lib/built-in.o: In function `fdtdec_get_config_int':
/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/lib/fdtdec.c:875: undefined reference to `fdt_path_offset'
lib/built-in.o: In function `fdtdec_get_config_string':
/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/lib/fdtdec.c:902: undefined reference to `fdt_path_offset'
/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/lib/fdtdec.c:906: undefined reference to `fdt_getprop'
/home/xxx/NuvotonWorkspace/output-sd-ext4/host/usr/bin/arm-nuvoton-linux-uclibcgnueabi-ld.bfd: BFD (GNU Binutils) 2.26.1 assertion fail elf32-arm.c:8437
/home/xxx/NuvotonWorkspace/output-sd-ext4/host/usr/bin/arm-nuvoton-linux-uclibcgnueabi-ld.bfd: BFD (GNU Binutils) 2.26.1 assertion fail elf32-arm.c:8437
/home/xxx/NuvotonWorkspace/output-sd-ext4/host/usr/bin/arm-nuvoton-linux-uclibcgnueabi-ld.bfd: BFD (GNU Binutils) 2.26.1 assertion fail elf32-arm.c:8437
/home/xxx/NuvotonWorkspace/output-sd-ext4/host/usr/bin/arm-nuvoton-linux-uclibcgnueabi-ld.bfd: error: required section '.rel.plt' not found in the linker script
/home/xxx/NuvotonWorkspace/output-sd-ext4/host/usr/bin/arm-nuvoton-linux-uclibcgnueabi-ld.bfd: final link failed: Invalid operation
Makefile:1210: recipe for target 'u-boot' failed
make[2]: *** [u-boot] Error 1
package/pkg-generic.mk:216: recipe for target '/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/.stamp_built' failed
make[1]: *** [/home/xxx/NuvotonWorkspace/output-sd-ext4/build/uboot-master/.stamp_built] Error 2
Makefile:76: recipe for target '_all' failed
make: *** [_all] Error 2`

**Comment by ychuang3** [comment]
NUC980 U-Boot does not support device tree.
Copying device tree files from linux dts will not work, because the drivers in u-boot even not support it.

**Comment by RSTurgay** [comment]
Thank You for reply.
