### ISSUE TITLE
Make file not work.

### ISSUE THREAD

**Issue by gianrftcc** [OpenNuvoton/NUC970_Buildroot#36]
Makefile present this error..

```
make[1]: Entering directory '/home/user/NUC970_Buildroot/output/build/applications-1.0.0/demos/CAN'
arm-linux-gcc -static can.c -o can_demo -lpthread -lc -lgcc
/usr/local/arm_linux_4.8/usr/bin/../libexec/gcc/arm-nuvoton-linux-uclibcgnueabi/4.8.5/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
Makefile:11: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/user/NUC970_Buildroot/output/build/applications-1.0.0/demos/CAN'
package/pkg-generic.mk:216: recipe for target '/home/user/NUC970_Buildroot/output/build/applications-1.0.0/.stamp_built' failed
make: *** [/home/user/NUC970_Buildroot/output/build/applications-1.0.0/.stamp_built] Error 1
```

Any possible solutions ?

**Comment by ychuang3** [comment]
I just clone this buildroot and run 'make nuvoton_nuc972_defconfig' -> 'make'.
It looks fine and works well.

**Comment by gianrftcc** [comment]
Cloned this repo, make nuvoton_nuc972_defconfig and then 'make'

Same error....

**Comment by ychuang3** [comment]
Please inspect you error message and find soltuion by seraching web, example ==>
https://stackoverflow.com/questions/51288467/cannot-open-libmpfr-so-4-after-update-on-ubuntu-18-04

Or, create docker and build under docker. It's strongly suggested to build under docker.

https://www.nuvoton.com/resource-download.jsp?tp_GUID=UG132022111403065318&currentFolder=/products/microprocessors/arm-cortex-a35-mpus/ma35d1-high-performance-edge-iiot-series/

Please follow section 2.1 to create the docker.
