### ISSUE TITLE
Unescaped left brace in regex is illegal here in regex

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC970_Buildroot#4]
When building alsa in Buildroot, automake fails with the error: "Unescaped left brace in regex is illegal here in regex"

This is because recent versions of Perl (I'm on 5.26) don't support unescaped braces. The solution is to modify line 3936 of automake from this:
`$text =~ s/\${([^ \t=:+{}]+)}/substitute_ac_subst_variables_worker ($1)/ge;`
to this:
`$text =~ s/\$\{([^ \t=:+\{\}]+)\}/substitute_ac_subst_variables_worker ($1)/ge;`

**Comment by yachen** [comment]
Hi, eb1c1fd should fix this issue. Thanks.
