### ISSUE TITLE
Missing configs for NUC980 boards

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC970_Buildroot#5]
Buildroot is missing defconfig files for individual NUC980 boards. It looks like different dev boards have different boot strategies, requiring u-boot to be built on a per-board basis. None of this is documented anywhere, and there's only one "nuvoton_nuc980_defconfig" file that's not clear about which board (IoT? EVK? Serial server?) it supports since it only uses the "nuc980" u-boot config, which (I think?) targets parallel NAND flash booting.

**Comment by yachen** [comment]
Hi,

Kernel/U-Boot config for individual boards are in their configuration directory.
You can use linux-menuconfig or uboot-menuconfig to load the configuration for kernel or u-boot. Thanks.


Sincerely,

Yi-An Chen

**Comment by jaydcarlson** [comment]
Thanks! I know how to load these configs manually — this is more of a feature request than a support request. If you want users to have a good out-of-box experience with the NUC980 ecosystem, they should be able to get a ready-to-burn image out of Buildroot for their specific dev board without having to mess around with manual configuration. This is how most other SoC vendors handle things.

**Comment by yachen** [comment]
Thanks for the feedback. We'll add config for NUC980 IoT board and Eth2UART board in buildroot. 


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Hi, config for these two boards were added. Thanks.
