### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by asd617140123** [OpenNuvoton/NUC970_Buildroot#6]
Hi,
HI,
  below is my error message,can you help me fix?  thanks

Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-19 07:22:27 ERROR 404: Not Found.

package/pkg-generic.mk:128: recipe for target '/home/eric/CY_NUC97/nuc970bsp-release-20170901/nuc970bsp-release-20170901/BSP/nuc970bsp/buildroot/output/build/applications-1.0.0/.stamp_downloaded' failed
make: *** [/home/eric/CY_NUC97/nuc970bsp-release-20170901/nuc970bsp-release-20170901/BSP/nuc970bsp/buildroot/output/build/applications-1.0.0/.stamp_downloaded] Error 1

**Comment by yachen** [comment]
Is your Linux machine behind a firewall?

**Comment by asd617140123** [comment]
Hi
   I think the problem is about perl version.
I have solved.

thank your reply
