### ISSUE TITLE
NUC977 kernel can not boot

### ISSUE THREAD

**Issue by asd617140123** [OpenNuvoton/NUC970_Buildroot#7]
Hi ,
     I use 977 mcu,below is my step
1.make nuvoton_nuc977_defconfig
2.make and generate uImage
3.I burn in board ,I can see boot kernel can occurpt some error

![linux_977error](https://user-images.githubusercontent.com/18673071/63645686-8f6da600-c736-11e9-8b8f-b52edd17fa00.png)

**Comment by yachen** [comment]
Are you testing the image on DEV board?

Yi-An Chen

________________________________

**Comment by asd617140123** [comment]
Yes , Can  I ask Uboot version has different?
because I see 2013 and 2016. which one do I use?

**Comment by yachen** [comment]
Please use 2016. We don't main 2013 now.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
I'm not seeing this issue. What U-Boot version are you using? 2013 or 2016? Did you modify any configuration?

U-Boot 2016.11-g7354727 (Sep 07 2018 - 14:11:14 +0800)

CPU: NUC977
Board: NUC977
DRAM:  64 MiB
NAND:  128 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   Net Initialization Skipped
No ethernet found.
=> nboot 0x7fc0 0 0x200000

Loading from nand0, offset 0x200000
   Image Name:   Linux-3.10.108+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    6461720 Bytes = 6.2 MiB
   Load Address: 00008000
   Entry Point:  00008000
=> bootm 0x7fc0
## Booting kernel from Legacy Image at 00007fc0 ...
   Image Name:   Linux-3.10.108+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    6461720 Bytes = 6.2 MiB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
   XIP Kernel Image ... OK

StartiBooting Linux on physical CPU 0x0
Initializing cgroup subsys cpuset
Initializing cgroup subsys cpu
Initializing cgroup subsys cpuacct
Linux version 3.10.108+ (andy@YA-T470P) (gcc version 4.8.5 (Buildroot 2016.11.1-                                                                                                                                                                                               gff4ccf9) ) #368 PREEMPT Mon Aug 26 15:49:41 CST 2019
CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=00053177
CPU: VIVT data cache, VIVT instruction cache
Machine: NUC970
Memory policy: ECC disabled, Data cache writeback
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
Kernel command line: root=/dev/ram0 console=ttyS0,115200n8 rdinit=/sbin/init mem                                                                                                                                                                                               =64M
PID hash table entries: 256 (order: -2, 1024 bytes)
Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
<snip...>

**Comment by asd617140123** [comment]
Hi I use 2013 uboot,and now I can normal boot the kernel now,thanks your reply.
By the way, your 2016ver uboot is   "https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11"?

**Comment by yachen** [comment]
Yup, that's the link. Please use v2016 unless there's specific reason to stick with v2013. Thanks.


Sincerely,

Yi-An Chen
