### ISSUE TITLE
nuc980dr 使用nandflash

### ISSUE THREAD

**Issue by cxelove** [OpenNuvoton/NUC970_Buildroot#9]
nuc980dr 64pin的nand控制器少了r/b引脚，该怎么使用nandflash呢？

**Comment by yachen** [comment]
Hi, 文件的說明有誤. 64 pin 的包裝缺了 r/b 無法支援 NAND flash.

**Comment by yachen** [comment]
Hi, 請下載新版文件. 應有說明 64 pin 包裝只支援 SPI NOR boot.

**Comment by cxelove** [comment]
谢谢您的回复，确实只支持spinor启动。
但是64脚的有NAND控制器，我硬件上连了一个mt29的nand，wp直接接高，cs接低，rb没有连接，修改驱动的static int nuc980_check_rb(struct nuc980_nand_info *nand)函数，直接改成udelay(60)是可以正常识别nand芯片。
现在我想改成读取nand的STATUS寄存器
write_cmd_reg(nand, NAND_CMD_STATUS);
int statusreg = read_data_reg(nand)
再检查rb位，
可以读出来，但是会导致后面其它读取的一直是这个寄存器的值，比如statusreg&nbsp;值为e0(rb状态是第6位为1)，后面程序读取的ID也全是E0。。。。。。
尝试读取之后使用write_addr_reg(nand, ENDADDR);和写nand的00命令，可是没有效果。
请问您有什么方法可以读取NAND芯片的STATUS寄存器不影响后面操的的方法吗？
麻烦您帮忙看一下或者试验一下。
这是dr上面使用udelay(60)时的状态








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi-An Chen"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 晚上6:02
收件人: "OpenNuvoton/NUC970_Buildroot"<NUC970_Buildroot@noreply.github.com&gt;; 
抄送: "眼捔锝y1滴淚"<chenxianen@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenNuvoton/NUC970_Buildroot] nuc980dr 使用nandflash (#9)





 
Hi, 請下載新版文件. 應有說明 64 pin 包裝只支援 SPI NOR boot.

**Comment by yachen** [comment]
Read Status 命會打斷原本NAND flash 的狀態. 以下是一份 NAND flash datasheet 的說明. 建議要用 NAND flash 的話找較多管腳的型號.
The command register remains in Status Read mode until further commands are issued. Therefore, if the Status Register is read during a random read cycle, the read command (00h) must be issued before starting read cycles.

**Comment by cxelove** [comment]
非常感谢！我知道怎么处理了，用一个普通IO去连应该就可以了，再次感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yi-An Chen"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 下午2:06
收件人: "OpenNuvoton/NUC970_Buildroot"<NUC970_Buildroot@noreply.github.com&gt;; 
抄送: "眼捔锝y1滴淚"<chenxianen@vip.qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenNuvoton/NUC970_Buildroot] nuc980dr 使用nandflash (#9)





 
Read Status 命會打斷原本NAND flash 的狀態. 以下是一份 NAND flash datasheet 的說明. 建議要用 NAND flash 的話找較多管腳的型號.
 The command register remains in Status Read mode until further commands are issued. Therefore, if the Status Register is read during a random read cycle, the read command (00h) must be issued before starting read cycles.
